# Generated by Django 5.1.7 on 2025-05-24 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_post_file_alter_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, choices=[('inaccurate_diagnosis', 'Inaccurate Diagnosis – The post shows incorrect or misleading disease detection.'), ('offensive_content', 'Offensive or Inappropriate Content – The post contains language or images that are not appropriate.'), ('spam_irrelevant', 'Spam or Irrelevant Information – The post is unrelated to wheat rust or is promotional.'), ('duplicate_post', 'Duplicate or Repetitive Post – This content has already been posted.'), ('misleading_image', 'Fake or Misleading Image – The image is edited, not real, or doesn’t match the claim.')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.post')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
