# Generated by Django 5.1.7 on 2025-05-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_postreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreport',
            name='severity_score',
            field=models.IntegerField(default=0),
        ),
    ]
