# Generated by Django 5.1.7 on 2025-05-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_remove_post_audio_remove_post_file_post_audio_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image_url',
        ),
    ]
