# Generated by Django 5.1.7 on 2025-05-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_rename_image_post_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreport',
            name='severity_score',
        ),
        migrations.AddField(
            model_name='post',
            name='severity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postreport',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
