# Generated by Django 5.1.7 on 2025-04-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='certificate',
            field=models.FileField(upload_to='certificates/'),
        ),
    ]
