# Generated by Django 5.1.7 on 2025-04-25 20:04

import authentication.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=authentication.storage_backends.SupabaseStorage, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='certificate',
            field=models.FileField(storage=authentication.storage_backends.SupabaseStorage, upload_to='certificates/'),
        ),
    ]
