# Generated by Django 5.1.7 on 2025-03-25 02:04

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=32),
        ),
    ]
