# Generated by Django 5.1.7 on 2025-05-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='warnings_count',
            field=models.IntegerField(default=0),
        ),
    ]
